version: '3.8'

services:
  frontend:
    image: maheshpohekar/frontend:v1.0
    ports:
      - "80:80"  
    depends_on:
      - backend

  backend:
    image: maheshpohekar/backend:v1.0
    ports:
      - "8080:8080"  
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/car_rental_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root

  database:
    image: mysql:latest
    ports:
      - "3307:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_rental_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
