name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Adjust branch to trigger workflow on

jobs:
  build:
    runs-on: ubuntu-latest  # Adjust runner OS if needed
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./car_rental_system/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend-image:latest
      # Build backend image
      # - name: Build backend image
      #   working-directory: ./car_rental_system
      #   run: docker build -t maheshpohekar/backend-image:latest --cache-from maheshpohekar/backend:v1.0 .

      # - name: Push images (optional)  # Only if backend image exists
      #   run: |
      #     docker push maheshpohekar/backend-image:latest
    
      # Build frontend image
      - name: Install dependencies (frontend)
        working-directory: ./car_rental_system_frontend  
        run: npm install
      - name: Build frontend image
        working-directory: ./car_rental_system_frontend  
        run: docker build -t maheshpohekar/frontend-image:latest .


      - name: Login to Docker Hub (optional)
        if: env.DOCKER_USERNAME  # Only if Docker Hub username provided
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push images (optional)  # Only if backend image exists
        run: |
          docker push maheshpohekar/frontend-image:latest
