name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Adjust branch to trigger workflow on

jobs:
  build:
    runs-on: ubuntu-latest  # Adjust runner OS if needed
    steps:
      - uses: actions/checkout@v3

      # Build backend image
      - name: Build backend image
        working-directory: ./car_rental_system
        run: docker build -t maheshpohekar/backend-image:latest .
      
        # Build frontend image
      - name: Install dependencies (frontend)
        working-directory: ./car_rental_system_frontend  # Change to your frontend directory
        run: npm install
      - name: Build frontend image
        working-directory: ./car_rental_system_frontend  # Change to your frontend directory
        run: docker build -t maheshpohekar/frontend-image:latest .  # Replace with your username and tag

  deploy:  # Optional deployment job (add after build succeeds)
      runs-on: ubuntu-latest
      needs: build  # Only run deploy after successful build
      steps:
        - uses: actions/checkout@v3
        - name: Login to Docker Hub (optional)
          if: env.DOCKER_USERNAME  # Only if Docker Hub username provided
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Push images (optional)
          run: |
            docker push maheshpohekar/backend-image:latest
            docker push maheshpohekar/frontend-image:latest  
