name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Adjust branch to trigger workflow on

jobs:
  build:
    runs-on: ubuntu-latest  # Adjust runner OS if needed
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub (optional)
        if: env.DOCKER_USERNAME  # Only if Docker Hub username provided
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Build backend image
      - name: Build backend image
        working-directory: ./car_rental_system
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-image:latest .
      - name: Push backend images  # Only if backend image exists
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-image:latest
    
      # Build frontend image
      - name: Install dependencies (frontend)
        working-directory: ./car_rental_system_frontend  
        run: npm install
      - name: Build frontend image
        working-directory: ./car_rental_system_frontend  
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-image:latest .


      # - name: Login to Docker Hub (optional)
      #   if: env.DOCKER_USERNAME  # Only if Docker Hub username provided
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push images (optional)  # Only if backend image exists
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-image:latest
